io:
  jirsis:
    drzewo:
      gallery-path: /Users/inaki.reta/Documents/proyectos/drzewo/gallery/img
      thumbnail:
        width: 75
        height: 75
      pageSize: 15
spring:
  data:
    mongodb:
      database: drzewo